export  const Fakeusers = [
  {
    id: 1,
    fullName: 'John Doe',
    email: 'john@example.com',
    role: 'member',
    phone: '123-456-7890',
    subscription: 'monthly',
    subscriptionStart: '2025-05-01',
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    email: 'jane@example.com',
    role: 'coach',
    phone: '987-654-3210',
    specialty: 'Yoga',
    experience: 5,
  },
  {
    id: 3,
    fullName: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    role: 'member',
    phone: '555-123-4567',
    subscription: 'yearly',
    subscriptionStart: '2025-01-10',
  },
  {
    id: 4,
    fullName: 'Bob Brown',
    email: 'bob.brown@example.com',
    role: 'coach',
    phone: '555-987-6543',
    specialty: 'Fitness',
    experience: 8,
  },
  {
    id: 5,
    fullName: 'Charlie Green',
    email: 'charlie.green@example.com',
    role: 'member',
    phone: '555-222-3333',
    subscription: 'monthly',
    subscriptionStart: '2025-03-15',
  },
  {
    id: 6,
    fullName: 'Diana Prince',
    email: 'diana.prince@example.com',
    role: 'coach',
    phone: '555-444-5555',
    specialty: 'Pilates',
    experience: 3,
  },
  {
    id: 7,
    fullName: 'Eve Adams',
    email: 'eve.adams@example.com',
    role: 'member',
    phone: '555-666-7777',
    subscription: 'yearly',
    subscriptionStart: '2025-02-20',
  },
  {
    id: 8,
    fullName: 'Frank Miller',
    email: 'frank.miller@example.com',
    role: 'coach',
    phone: '555-888-9999',
    specialty: 'Crossfit',
    experience: 6,
  },
  {
    id: 9,
    fullName: 'Grace Lee',
    email: 'grace.lee@example.com',
    role: 'member',
    phone: '555-000-1111',
    subscription: 'monthly',
    subscriptionStart: '2025-04-05',
  },
  {
    id: 10,
    fullName: 'Henry Ford',
    email: 'henry.ford@example.com',
    role: 'coach',
    phone: '555-222-4444',
    specialty: 'Boxing',
    experience: 10,
  },
  {
    id: 11,
    fullName: 'Ivy King',
    email: 'ivy.king@example.com',
    role: 'member',
    phone: '555-333-5555',
    subscription: 'yearly',
    subscriptionStart: '2025-05-10',
  },
  {
    id: 12,
    fullName: 'Jack White',
    email: 'jack.white@example.com',
    role: 'coach',
    phone: '555-666-8888',
    specialty: 'HIIT',
    experience: 4,
  },
];