# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  BACKEND_IMAGE: "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA"
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA"
  MANIFESTS_REPO: "git@gitlab.com:elfaouzi/weather-manifests.git"

# Docker-in-Docker
services:
  - docker:20-dind

# === DEFAULT: Only for build jobs ===
default:
  image: docker:20
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

# === TEST BACKEND (NO DOCKER) ===
# test-backend:
#   stage: test
#   image: golang:1.23-alpine
#   before_script: []  # <--- OVERRIDE: NO DOCKER LOGIN
#   script:
#     - cd go-backend-weatherapp-e12
#     - go test ./... -v
#   only: [main]

# # === TEST FRONTEND (NO DOCKER) ===
# test-frontend:
#   stage: test
#   image: node:20-alpine
#   before_script: []  # <--- OVERRIDE: NO DOCKER LOGIN
#   script:
#     - cd react-web-weatherapp-e12
#     - npm ci
#     - npm test -- --watchAll=false || true
#   only: [main]

# === BUILD BACKEND (NEEDS DOCKER) ===
# build-backend:
#   stage: build
#   script:
#     - cd go-backend-weatherapp-e12
#     - docker build -t $BACKEND_IMAGE .
#     - docker push $BACKEND_IMAGE
#   only: [main]

# === BUILD FRONTEND (NEEDS DOCKER) ===
build-frontend:
  stage: build
  script:
    - cd react-web-weatherapp-e12
    - docker build -t $FRONTEND_IMAGE .
    - docker push $FRONTEND_IMAGE
  only: [main]

# === DEPLOY: Update weather-manifests ===
update-manifests:
  stage: deploy
  image: alpine
  before_script: []
  script:
    - apk add --no-cache git yq
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/elfaouzi/weather-manifests.git /tmp/manifests
    - cd /tmp/manifests
    # - yq e -i ".spec.template.spec.containers[0].image = \"$BACKEND_IMAGE\"" k8s/deployment-backend.yaml
    - yq e -i ".spec.template.spec.containers[0].image = \"$FRONTEND_IMAGE\"" k8s/frontend.yaml
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Deploy $CI_COMMIT_SHORT_SHA"
    - git remote set-url origin https://oauth2:${MANIFESTS_TOKEN}@gitlab.com/elfaouzi/weather-manifests.git
    - git push origin HEAD:main
  only: [main]
    